# configuration file for dotnet-releaser
[msbuild]
project = "MonorailCss.SourceGen.AspNet.sln"
build_debug = true
[test]
run_tests_for_debug = true
[nuget]
publish_draft = true # publish draft NuGet package per commit
[github]
user = "monorailcss"
repo = "MonorailCss.SourceGen.AspNet"
